### ISSUE TITLE
Send commands from server to client

### ISSUE THREAD

**Issue by alexcoder04** [alexcoder04/rfap#1]
This is very likely never to be implemented: to achieve this, the client would have to be listening to the server all the time, so it couldn't send commands.

The only possible solution would be to open a second socket which would have to run in a separate thread that can communicate with the main thread, so the overall design would become much more complicated.

**Comment by BoettcherDasOriginal** [comment]
@alexcoder04 
there is a second solution: async functions

**Comment by alexcoder04** [comment]
Closing this for now, because there is not really a need for this.
